### ISSUE TITLE
Performance Test. 

### ISSUE THREAD

**Issue by schoening** [schteppe/p2.js#113]
Only found the library yesterday. I love it :) I created a very simple performance test:

https://dl.dropboxusercontent.com/u/53738503/p2performancetest/19-06-2014/index.html

I wanted to compare it to the Turbulenz engines 2D physics. And I am getting similar results.

http://biz.turbulenz.com/samples#sample-modal/samplepage/sample_assets/physics2d.canvas.release.html/samplesrc/sample_assets/physics2d.js.html

My test is not as elaborate yet. But I thought it could make a nice addition to the examples. (I suck at github and haven't uploaded it to any github repo yet)

Any performance tips ? I was thinking of doing a webworker version next.

**Comment by Appebyte** [comment]
Hi @schteppe 

Regarding your post:
> (All the things listed makes the engine a bit faster. Hope to make them default when they get more stable)

Based of your examples (for instance the circle container), it seems like changing these points to for instance the BODY_SLEEPING does in fact improve performance. Are the points you mentioned stable at this moment? If they are not, what kind of potential problems could occur?

**Comment by schteppe** [comment]
@Appebyte 

* SAPBroadphase is currently default and should be OK.
* Sleeping should be good, though there may be contact/constraint problems when bodies wake up or fall asleep. Not tested very much.
* Island splitting has known bugs when adding/removing objects during step(). But this is prevented in the master branch by throwing errors. Also, to be honest I'm not sure it will improve performance - needs more optimization.
* `world.solver.tolerance` will make the contact/constraint solver stop solving when the solution is "good enough". Try changing it on your scene and see what happens. Keep the number as large as possible.

**Comment by Appebyte** [comment]
@schteppe Thank you for your reply and truly great work on this physics engine!
