### ISSUE TITLE
Top-view car friction constraint

### ISSUE THREAD

**Issue by schteppe** [schteppe/p2.js#122]
Would be cool to have a constraint that adds friction in the "sideways" direction of a body. This could be used to make a top-down-view racing car.

Maybe it would be useful to make a Vehicle helper class too.

**Comment by Fishrock123** [comment]
@schteppe is this only applicable to that specific type of body?

**Comment by schteppe** [comment]
@Fishrock123 It should work with any dynamic body.. I guess you want to use it for your spaceship game?

**Comment by Fishrock123** [comment]
Maybe eventually, but I'm more just curious. I didn't look in the code in great detail, but it seemed more specific than something like just air friction.

**Comment by schteppe** [comment]
It's basically just a way to prevent sliding along a local axis. I'm sure it can be used for other things than just top down vehicles.

For example, it should be possible to implement Retry-like plane physics using this class.
