### ISSUE TITLE
One way platforms in p2.js

### ISSUE THREAD

**Issue by josimard** [schteppe/p2.js#123]
Hi, 
I am trying to figure out how I could make my character only collide with the up-side of a platform. (And also let the player drop down when the player is trying to go down)

I can imagine one-way shapes that would be useful to create collisions from one side only, is there something to achieve this already? 

Right now, in the pre-solve phase, I am trying to cancel the collision but I can't figure out how to deal with the contacts nor use a normal that makes sense to create a working scenario. In Box2D, we had to deal with a contact manifold to give us a "local" normal of each shape boundaries to cancel the collision. 

In Nape, there was an example to achieve just that, but I can't do it in p2.js:
https://github.com/deltaluca/www.napephys.com/blob/gh-pages/samples/OneWayPlatforms/OneWayPlatforms.hx

It would be nice to see it in action in the "Character.html" example.

Cheers,
Jo

**Comment by schteppe** [comment]
@josimard I added one way platforms to the character demo (examples/canvas/character.html): https://github.com/schteppe/p2.js/commit/4966305e4eab9dcd82f418873cd4b3d384b1d568
Might need some tweaking but it works :)
