### ISSUE TITLE
Forces cleared after first substep.

### ISSUE THREAD

**Issue by tapio** [schteppe/p2.js#137]
I noticed that the apparent speed of my simulation depends on the time step when using substepping even though the frame rate is solid 60fps. Digging a little, It seems the problem is that forces are auto-cleared at the end of `world.internalStep()`, so my manual forces are only accounted for during the first substep and not there during subsequent steps. Am I missing something? It is the same way in cannon.js btw.

For reference, [Bullet applies gravity to bodies before doing the substeps and clears forces after all steps are performed](https://github.com/bulletphysics/bullet3/blob/89aeae910239a6c0486f5936322cc6a326d52057/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp#L449-L464).

**Comment by schteppe** [comment]
I think @wellcaffeinated is right. Out-of-the-physics-loop interaction with bodies is not something that I want to encourage. You can already do this correctly using the ```postStep``` event:

```js
world.on("postStep", function(){
    body.force[0] = fx;
});
```
