### ISSUE TITLE
Upcoming release?

### ISSUE THREAD

**Issue by psalaets** [schteppe/p2.js#146]
Any estimate on when a new release of p2 will be published to npm? I am using p2 via npm/browserify.

There have been a few changes since the last version was pushed out, which was early July 2014.

Thanks

**Comment by schteppe** [comment]
Will do that whenever I get some time over. Meanwhile, why not point your package.json to the github repo?

**Comment by psalaets** [comment]
Totally forgot that I can point to repos, commits, etc. Thanks!

**Comment by schteppe** [comment]
No problem! Should include a short how-to in the readme. You're not the only one asking about this. Releases don't come very often for this hobby project of mine...

**Comment by psalaets** [comment]
Are there any tasks I could submit a PR for? I'm not great with physics but I can do general coding/housekeeping stuff.

**Comment by schteppe** [comment]
That's so nice of you to offer your coding time! Well.. Some of the things that take time are docs (keeping updated & clean) and code optimizations. But don't do that. Do something you think is fun instead. Have fun... or else :rage: lol
