### ISSUE TITLE
Continuous collision detection 

### ISSUE THREAD

**Issue by enriqueto** [schteppe/p2.js#149]
any plans for that?

**Comment by schteppe** [comment]
Probably in the future! Needs some work: capsule casting (maybe it can work with ordinary ray casting too) and binary searching for time of impact.

**Comment by enriqueto** [comment]
let me know if I can help, unfortunately I have no idea of how a physics engine works

**Comment by schteppe** [comment]
Well, if you decide to get familiar with p2, you could start porting the Cannon.js raycast methods and classes:

```js
CANNON.World.prototype.raycastAll
CANNON.World.prototype.raycastAny
CANNON.World.prototype.raycastClosest
CANNON.RaycastResult
CANNON.Ray
```

I think that regular rays are a good start. If not, it's still a great feature :)

**Comment by enriqueto** [comment]
Alright. Although I'm quite busy I'll take a look to those classes

**Comment by schteppe** [comment]
@enriqueto The classes and World methods are in place along with an example.

To do now is

1. using it for roughly detect collision. This is done just before integrating / updating position of bodies, if the body is moving fast.
2. Estimate time of impact, using binary search and the justTest flag in the Narrowphase.
3. Move the body to the time of impact.

Will continue working on this whenever I get some coding time over. I really want this feature for p2.js and cannon.js too :)

**Comment by enriqueto** [comment]
thanks, let see if I can understand that

**Comment by schteppe** [comment]
@enriqueto lol don't worry I got this :P

I got 1 and 3 in place now, and instead of 2 I just use the raycast hit point. Now I just need to implement binary searching for the time of impact to make it more accurate.

You should be able to use this feature now by building p2.js locally and setting ccdThreshold to 0 on the body. See the ccd demo. It won't be very accurate, but it will work better than nothing :)

**Comment by schteppe** [comment]
Added binary searching too! Should be working good now :)

**Comment by enriqueto** [comment]
Thanks, I felt a bit overwhelmed by that. I haven't got any experience programming game frameworks, just using them.
