### ISSUE TITLE
Objects constructors

### ISSUE THREAD

**Issue by mccraveiro** [schteppe/p2.js#150]
I have a project that is using ES6 modules with BabelJS. However, I can't extend P2 because the prototype is being changed and the constructor is not set. 

For example: [Body.js line 392](https://github.com/schteppe/p2.js/blob/master/src/objects/Body.js#L392)

Current code:
```javascript
Body.prototype = new EventEmitter();
```
After setting the constructor: 
```javascript
Body.prototype = new EventEmitter();
Body.prototype.constructor = Body;
```

Finally I can extend P2:
```javascript
class MyObject extends p2.Body {

}
```

**Comment by schteppe** [comment]
Makes total sense! I've not been consistent regarding this.
Go ahead if you want to submit a PR. It's just 22 straight forward lines to add :)
