### ISSUE TITLE
Physics shift in platformer sample

### ISSUE THREAD

**Issue by kosmom** [schteppe/p2.js#153]
FF 38
If switch browser tab when animation
 is start - some calculations brakes
and platforms KINEMATIC position jump on some length
for example in Platformer demo
![platformer](https://cloud.githubusercontent.com/assets/1491528/7221073/2ba842b8-e6e6-11e4-8f67-b97a95fd18ff.gif)

**Comment by schteppe** [comment]
Hi,

Yes, the platforms should be controlled depending on world.time and not the time value passed in by requestAnimationFrame. Fixing this would make it frame rate independent. Thanks for the heads up! Do you want to make a PR?

**Comment by schteppe** [comment]
Fixed in https://github.com/schteppe/p2.js/commit/2e149b2da749fd1eef8c9a348fe1342dca841eb6

**Comment by kosmom** [comment]
Still relevant
![fall](https://cloud.githubusercontent.com/assets/1491528/8639301/8507f3f0-28de-11e5-86ca-67ac3f4786c3.gif)

**Comment by schteppe** [comment]
The issue was fixed, but I didn't make a new release until now. Try refreshing and it should work better.
