### ISSUE TITLE
Raycasting and body.fromPolygon

### ISSUE THREAD

**Issue by wojciak** [schteppe/p2.js#157]
Hi,

Does raycasting work with polygon shapes? Can't seem to get any result.

**Comment by schteppe** [comment]
No, sorry. Ray only supports Plane, Circle and Rectangle this far. Adding Convex support would fix it.

**Comment by schteppe** [comment]
Quickly added it! Does it work?

**Comment by wojciak** [comment]
Wow - checking out now :)

**Comment by schteppe** [comment]
Awesome. You'll need to rebuild p2.js/ p2.min.js using ```grunt```, but I bet you're already doing that :)

**Comment by wojciak** [comment]
hehe yeah :) Basically works as expected - I only have a bit of a problem with 2 of my shapes but I'm quite certain that I blew the rendering somewhere :) 

I'll sit to it in the morning and post and update ;)

Attachment 1: this is ok
![screen shot 2015-04-27 at 21 57 59](https://cloud.githubusercontent.com/assets/4658815/7356442/78e5eb46-ed28-11e4-97dd-b89863036ee1.png)

Attachment 2: this is quirky - probably just a rendering issue or a bad polygon
![screen shot 2015-04-27 at 21 58 06](https://cloud.githubusercontent.com/assets/4658815/7356444/7d0278b6-ed28-11e4-9519-38422377256d.png)

**Comment by wojciak** [comment]
P.s. awesome work! :+1:

**Comment by wojciak** [comment]
Fixed polygons - works perfectly! :) :8ball:

**Comment by schteppe** [comment]
Sweet. Good luck with your game!
