### ISSUE TITLE
Custom body id

### ISSUE THREAD

**Issue by lgick** [schteppe/p2.js#161]
Hi!

I can use my ID with body instance?

Example:

```javascript
        var body = new Body({
            mass: 1,
            position: [0, 0],
            angle: 0,
            velocity: [0, 0],
            angularVelocity: 0
        });

   body.id = 'myPersonalID';
```
this code will work?

**Comment by schteppe** [comment]
Probably no. I'd suggest you to use some other property name. The id needs to be a unique integer, and you should not change it while the body is in the world.

**Comment by lgick** [comment]
Thank you!
