### ISSUE TITLE
RevoluteConstraint issue

### ISSUE THREAD

**Issue by mrjor** [schteppe/p2.js#164]
![screen shot 2015-06-17 at 21 10 12](https://cloud.githubusercontent.com/assets/886538/8216194/4bc634f6-1535-11e5-9507-39b2bc08c840.png)

Hi I am trying to create a chain with the RevoluteConstraint. Each chain is a body with a mass of 2. But as you can see in the screenshot the constraints doesn't stay at its point but are stretching a bit. How can i make this more like a Chain instead of a Elastic? I am already using stiffness to the world of 1000000.

**Comment by schteppe** [comment]
Hi,

I made a jsfiddle for you to play around with: http://jsfiddle.net/rnptmy1p/1/

Things you could try: 

1. Use more solver iterations
2. Use less relaxation
3. Add the constraints in the reverse order (might make it easier for the solver if the constraints iterate in the right order)
4. Use less gravity

Try that to begin with, let me know how it goes!

**Comment by mrjor** [comment]
Thanks that helped a lot.

**Comment by jstoeffler** [comment]
Having the same kind of issue: http://jsfiddle.net/gbdL9g0t/4/

The constraint breaks with:

- Constraint stiffness = Infinity
- Gravity = 0
- Constraint relaxation = 0
- Just 1 constraint
- Solver iterations : 1000

Ok, I agree it's quite an intense situation :) Reducing motor speed, or body mass helps, but I'm wondering whether there's a way to fix this?

**Comment by schteppe** [comment]
@jstoeffler Hmm.... You're using a Revolute with both limits and a motor... What exactly are you trying to do? Right now the motor and the limits will both use their max force against each other. You should remove either the motor or the limits. Or set a different max forces so one of the constraints can give in for the other.

**Comment by jstoeffler** [comment]
Well, I wanted to have a character "kicking" from 0 to 90°.

So the character's muscles would be emulated by the motor, and the flexibility would be emulated by the limit. That works in Unity, the motor is never as strong as the constraint. 

So I found another way to do it, I simply just use the constraint's limits, and set the desired angle.

I'm still curious about what you said:

> set a different max forces so one of the constraints can give in

Do you mean with the constraint's maxForce? Does it apply to the motor or the constraint? I've tried to play with it in my jsfiddle, and it has weird results...

**Comment by schteppe** [comment]
I see! You should set the max force of the motor to something smaller then. There's no method for it yet but it should probably be added.

```js
revolute.motorEquation.maxForce = 10;
revolute.motorEquation.minForce = -10;
```

Haven't tried this yet but it should work... Adjust the force magnitude to fit your simulation.

Both the limits and the motor are constraints (in a way), that's why I formulated it a bit weird. Sorry.

**Comment by jstoeffler** [comment]
Oh, great, it works thanks! My first thought is that a setter on the constraint would be convenient, but I haven't seen all the abstract parts of the framework yet, so I don't know if it would make sense.

**Comment by schteppe** [comment]
Fantastic! Yes, a setter would indeed be great :) Will create an issue.
