### ISSUE TITLE
Сreate static body with sizes

### ISSUE THREAD

**Issue by lgick** [schteppe/p2.js#167]
I create tiles game.

My code:

```js
var map = [
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
];
var step = 32;
var x, y, lenX, lenY, tile, body;
 
for (y = 0, lenY = map.length; y < lenY; y += 1) {
  for (x = 0, lenX = map[y].length; x < lenX; x += 1) {
    tile = map[y][x];

    if (tile === 1) {
      body = new p2.Body({
        position: [x * step, y * step],
        type: p2.Body.STATIC
      });

      body.addShape(new p2.Rectangle(step, step));
      world.addBody(body);      
  }
}
```

Result:

![2015-06-21 2 13 27](https://cloud.githubusercontent.com/assets/2997257/8269702/06ded304-17bd-11e5-9cc9-c9baaa019596.png)

Red lines - real size my tiles. But my tiles are created with width and height. 
Why is this happening?

Help! Thank you!

**Comment by schteppe** [comment]
Hi,

Your tiles have their position in the upper left corner and the bodies have their position in the center. So you need to add size/2 to x and y to the body position.

By the way, positive Y is up in p2, and probably down in your game... How do you solve that?

The rectangle size should be correct though... Not sure what happened there. Maybe you could copy one of the demos in the p2 repo (see demos/), paste in your code and see what's up.

While I think this solution of yours is a good start, I also think that you should merge your rectangle bodies to get better physics performance. The scene you have in this example can be made with 4 long rectangle bodies, which should be much more performant.
This merge part should be possible to make automatic, but I don't have code for that, sorry.

**Comment by schteppe** [comment]
This is how the scene looks in a p2 Demo. Don't think there's any problem with the size, just the offset.

![skarmavbild 2015-06-21 kl 19 00 02](https://cloud.githubusercontent.com/assets/1063152/8272555/c5c8d5f0-1847-11e5-9a2f-7c30d871d3c3.png)

**Comment by lgick** [comment]
With offset (to add size/2) - it works! Thank you!
You are right, positive Y goes down, but at the moment it works normal with p2.

Yes, I will combine tiles into blocks! Thanks!

**Comment by schteppe** [comment]
Nice!
