### ISSUE TITLE
Ray Casting For Polygons

### ISSUE THREAD

**Issue by noelb** [schteppe/p2.js#176]
Hi,

I'm trying to get raycasting working for polygons and wasn't having any luck. 

I noticed that the capsule in the live example doesn't appear to work:
https://schteppe.github.io/p2.js/examples/canvas/raycasting.html

And the pentagram in the example included in the current build doesn't work either.
https://github.com/schteppe/p2.js/blob/master/examples/canvas/raycasting.html

Still in progress or am I doing something wrong?

Thanks.

![screen shot 2015-07-06 at 4 49 29 pm](https://cloud.githubusercontent.com/assets/169229/8517027/17bec2f8-23ff-11e5-9ded-de51d00a5147.png)

**Comment by schteppe** [comment]
Hi,

It's in progress. The most recent version should work though. Try rebuilding p2.js locally (npm install && grunt) and run the same example.

Beware: the raycasting API is about to change soon.

**Comment by noelb** [comment]
Thanks Stefan. Looking forward to the raycasting updates, p2js is pretty fantastic.

**Comment by schteppe** [comment]
Thanks! Check out the [new release](https://github.com/schteppe/p2.js/releases/tag/v0.7.0). The live [raycasting demo](https://schteppe.github.io/p2.js/examples/canvas/raycasting.html) should work now!
