### ISSUE TITLE
Circles look ugly in some demo(s?)

### ISSUE THREAD

**Issue by 1j01** [schteppe/p2.js#181]

**Comment by schteppe** [comment]
I'm guessing you're referring to the slightly non-circular canvas circles?

**Comment by 1j01** [comment]
Yes. I was planning on providing a description, but this got submitted apparently.

And it doesn't seem to be happening anymore... Maybe it was a chrome bug?

**Comment by 1j01** [comment]
Yes, apparently this was just a browser issue.
