### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by instantia** [schteppe/p2.js#182]
Do not installing in nodejs.
npm install --save --no-bin-links p2
Error:
https://gist.github.com/instantia/5a9f6864cbb601dc798f

**Comment by schteppe** [comment]
How can this be fixed?

**Comment by instantia** [comment]
Think I found the solution. This vagrant + windows. Max path limit 256 symbols.

**Comment by instantia** [comment]
So, as vagrant not fixed a bug UNC path Windows.
My solution was:
shell script 
<pre>config.vm.provision :shell, :path => "scripts/mounts.sh", run: "always"</pre>
<pre>
echo "Mounting node_modules to home folder"
mkdir -p ~/www/dev/roamforge/node_modules && mkdir -p /vagrant/www/dev/roamforge/node_modules && sudo mount -o bind ~/www/dev/roamforge/node_modules /vagrant/www/dev/roamforge/node_modules
</pre>
