### ISSUE TITLE
Unclear documenation

### ISSUE THREAD

**Issue by trsh** [schteppe/p2.js#188]
boxShape = new p2.Box({ width: 2, height: 1 });

I can find a place in docs, where is written what stands for "width: 2, height: 1". What are the units?

**Comment by Quadra-Kill** [comment]
Core concepts from wiki：
“Units A unit is a way of measuring quantities such as length and time. In p2.js, we use meters-kilogram-second (MKS) units, and radians are used for angles. Do not use pixels for units.”

**Comment by Quadra-Kill** [comment]
I`m from China,just a little English.
The p2.js is a very good physical engine,and there was a famous h5 game engine .Inc that recommend p2.js for their user.
Thanks schteppe!
Also,I help students who were interested in P2.js can make yours contributions to  this big and beauty`s  physical engine.
Thanks schteppe!

**Comment by schteppe** [comment]
Hello!
Yes, you found the answer yourself. It's meters.

**Comment by schteppe** [comment]
Thanks @Quadra-Kill !

Writing the units for each documentation entry is tedious. That's why it's left out in most places.
