### ISSUE TITLE
this is a big and beauty engine

### ISSUE THREAD

**Issue by Quadra-Kill** [schteppe/p2.js#189]
I`m from China,just a little English. 
The p2.js is a very good physical engine,and there was a famous h5 game engine .Inc that recommend p2.js for their user. 
Thanks schteppe!
 Also,I help students who were interested in P2.js can make yours contributions to this big and beauty physical engine.
Thanks schteppe!

**Comment by schteppe** [comment]
I'm super glad you find it useful! Let me know if I can help get you started.

What engine recommended you p2? Was it the Egret engine?

Thanks.

**Comment by Quadra-Kill** [comment]
yes,it is egret

**Comment by Quadra-Kill** [comment]
I learning egret for develop game,so i know p2.js

**Comment by schteppe** [comment]
Awesome! Nice work on the wiki!

**Comment by jstoeffler** [comment]
+1

I think this repo needs more stars, it would help people making their choices (I actually come back from Matter.js, which I chose because of the popularity, but has a lot of limitations).
