### ISSUE TITLE
Body.fromPolygon empties my path array.

### ISSUE THREAD

**Issue by jstoeffler** [schteppe/p2.js#192]
There's quite a few cases where it can be useful to reuse your paths, but apparently when I call Body.fromPolygon, my paths arrays are emptied. Example:

            var legPath = // My character's beautiful leg shape :)
            var frontLeg = new p2.Body({
                // some properties
            });
            var backLeg = new p2.Body({
                // some properties
            });
            frontLeg.fromPolygon(legPath);
            // at this time my beautiful leg path is an empty array :(
            backLeg.fromPolygon(legPath);

Some people also consider it's a bad practice to modify the function arguments unless it's explicit (and I agree, it's probably something you don't expect).

**Comment by schteppe** [comment]
Thanks for the heads up! Should work as expected now.

**Comment by jstoeffler** [comment]
Thank you for the quick update! It's really a wonderful project, I hope I'll be able to contribute in the future :)

**Comment by schteppe** [comment]
Awesome, thanks!
