### ISSUE TITLE
impact vs. beginContact

### ISSUE THREAD

**Issue by gaufqwi** [schteppe/p2.js#201]
This is really a usage question not an issue, but I couldn't find a more appropriate place to ask.

What is the difference between the beginContact event and the impact event?

**Comment by schteppe** [comment]
The biggest difference is that the beginContact event is run before constraint solve and body integration. In other words: the beginContact event can be used to disable contacts before they are solved.

It also looks like impact event will run once per contact point, and the beginContact once per shape pair.

The begin/endContact events makes the impact event superfluous to me. Should probably be deprecated.

**Comment by gaufqwi** [comment]
Thank you.

Is there a better place to ask usage questions like this? I hate to clutter up the issues database.

**Comment by schteppe** [comment]
No problemo :)

I think, this is the best (and only?) place to ask for now. Maybe you could ask in http://html5gamedevs.com forum too but that is more aimed towards different gamedev frameworks.

**Comment by schteppe** [comment]
Deprecated it here: https://github.com/schteppe/p2.js/commit/605e61042e34794e6fb48b8d8f2f48e3631cdb46#diff-cac728b68c876a87af597924712ea409R219
