### ISSUE TITLE
Cloth

### ISSUE THREAD

**Issue by tracend** [schteppe/p2.js#205]
Great lib. Maybe I missed it but I haven't seen any cloth simulation. Do you have plans for that? 

How about incorporating some of this logic (with proper credit of course) 
https://github.com/Dissimulate/Tearable-Cloth/blob/master/Cloth.js

Cheers

**Comment by schteppe** [comment]
Thanks! No not really, but I agree it would be cool to have such demo.

Note that p2 wouldn't be able to compete performance-wise with other libs dedicated to cloth simulation. To get nearly as good performance, one would need to be able to turn off the Broadphase completely, as well as anything that has to do with rotation.

**Comment by tracend** [comment]
I see. So would you propose to use another lib for cloth simulation (which in most cases would be for visual effect) and keep p2 ligthweight so it can be more performant dealing with the _core_ physics?

**Comment by schteppe** [comment]
Yes. It would need a lot of specialized code for p2 to keep up.

If you only need cloth sim and no collisions and no rotation, no inertia or shapes, then using something else would reduce download and increase performance greatly. But if you need a cloth interacting with rigid bodies, then use p2.

**Comment by tracend** [comment]
Cool, tnx for the heads up.
