### ISSUE TITLE
GSSolver.solve Deoptimization?

### ISSUE THREAD

**Issue by jtenner** [schteppe/p2.js#214]
![Deoptimization](http://i.snag.gy/yfaPY.jpg)

Looks like you could get a performance boost in chrome by tweaking this function.  I'm not sure exactly what it is.  The profiler says it makes a "Call to a Javascript runtime function."

Looks like this one is going to be fun.

**Comment by schteppe** [comment]
Weird, I didn't get that warning myself. Which Chrome version and which demo? Maybe I have to enable a flag in devtools to get this warning? Thanks.

**Comment by jtenner** [comment]
Yeah totally. This hasn't happened before, but I happen to be testing my application in chrome canary.

Chrome Version 51.0.2672.0 canary (64-bit)

**Comment by jtenner** [comment]
I wanted to readdress this issue, because I can't reproduce it.

It may have been a chrome bug.

Glad this is over.

Thanks,
-Josh
