### ISSUE TITLE
Scaling/rotating a body from a polygon?

### ISSUE THREAD

**Issue by AndrewRayCode** [schteppe/p2.js#220]
I have a series of points that define the outline of a wall. I'm using `body.fromPolygon(points)`. 

I'd like to make multiple copies of this wall that are scaled / rotated. Do I have any options other than re-creating the polygon points at each new scale/rotation? With box shaped walls it's easy because I can give the shape a `width` and `height`.

**Comment by schteppe** [comment]
The latest master version makes a copy of the path array, so you can re-use the array of points. For different rotations, you can simply set the rotation on the Body or the Shape, and re-use the same path array. For different scales, I'm afraid you'll have to make a new path array each shape.

Under the hood, all the data is copied and cannot be reused in between bodies. I guess this is a good place for improvement - maybe implementing something like the box2d fixtures could help. With a fixture to attach a shape to a body, the shape data could probably be re-used easily. However, I'm not sure if it would solve the scale problem.

**Comment by jtenner** [comment]
@DelvarWorld would a simple module that scales/rotates/translates points be helpful?  I've been meaning to write one.

**Comment by DelvarWorld** [comment]
@jtenner the internal [vec2 library for p2.js](http://schteppe.github.io/p2.js/docs/classes/vec2.html) already has all of those method. I was just hoping I could be even lazier out of the box :)

**Comment by jtenner** [comment]
Yeah but you have to map each coordinate to each transform in order instead of making a single transform and transforming a set of points.

I know vec2 exists, but I'm talking about making something fully featured.

**Comment by MaxPleaner** [comment]
I am not sure how to write any scale functions in terms of changing the points list. But scale / anchor changes are useful and the hitboxes (polygons) are not updating as a result. If someone could show an example, I'd appreciate it.

**Comment by MaxPleaner** [comment]
I'll give an example. Gif 1 is using the 1:1 scale sprite and the collision is correct at the bottom the screen. Gif 2 using 0.5 scale and the hitbox is no longer correct:

![bug1](https://cloud.githubusercontent.com/assets/5035719/24519519/5456647c-153a-11e7-99ec-950bbc619463.gif)

![bug2](https://cloud.githubusercontent.com/assets/5035719/24519521/567ddaaa-153a-11e7-8750-256993bc9859.gif)
