### ISSUE TITLE
IslandManager - Cannot read property 'neighbors' of undefined

### ISSUE THREAD

**Issue by hapticdata** [schteppe/p2.js#223]
Hello,

I am running into an issue where periodically an error is thrown in [IslandManager#split(world) on line 168](https://github.com/schteppe/p2.js/blob/master/src/world/IslandManager.js#L168). Occasionally `bodies.indexOf(eq.bodyB)` is returning _-1_. It appears to happen when I have created a very-large shape.

My scene is basically 2 planes for sides and a floor that I periodically remove and then remove any bodies that have fallen below the floor.

thanks for all of your hard work, p2.js is great!

**Comment by schteppe** [comment]
Hi,
The easy way is to set world.islandSplit to false and this should not happen.
Do you have constraints on the bodies you remove? Then you need to remove the constraints first.

**Comment by schteppe** [comment]
Also, do you use the collision events to remove bodies? Try doing the removal in the update loop instead. See https://github.com/schteppe/p2.js/pull/208#issuecomment-184023675

**Comment by hapticdata** [comment]
Thanks, `world.islandSplit = false` worked for my use case.
The bodies do have constraints on them. I was removing them in the update loop. I was removing the bodies before the constraints, but they were sequential operations. Maybe that was it.

thanks so much!
