### ISSUE TITLE
Running a headless simulation as fast as possible?

### ISSUE THREAD

**Issue by TobLoef** [schteppe/p2.js#235]
For a project I'm working on I would like to do some "off-camera", or headless, physics simulations, as fast as possible of course. The simulation loop wouldn't be tied to any graphics update and should go as fast as the CPU would allow. How can I do this?

Thank you.

**Comment by schteppe** [comment]
Hi. Just run `world.step(dt)` in a for loop? Check the current time using `world.time`.

**Comment by TobLoef** [comment]
@schteppe Great, thanks! I can't believe it was that simple. Really looking forward to working more with p2.js.
