### ISSUE TITLE
Circular dependency between Ray and RaycastResult

### ISSUE THREAD

**Issue by AndrewRayCode** [schteppe/p2.js#249]
[Ray.js requires RaycastResult](https://github.com/schteppe/p2.js/blob/master/test/collision/Ray.js#L6), even though it's not used as far as I can tell, and [RaycastResult.js requires Ray](https://github.com/schteppe/p2.js/blob/master/test/collision/RaycastResult.js#L4).

I'm working on a tool to detect cyclical requires in nodejs projects and it detected this one. I think the require can just be removed from Ray.js?

**Comment by schteppe** [comment]
I think you accidentally mistook the unit test files (`test/`) for the source files (`src/`)?
