### ISSUE TITLE
Inaccurate statement in collision filtering wiki?

### ISSUE THREAD

**Issue by danneu** [schteppe/p2.js#250]
The [collision filtering wiki](https://github.com/schteppe/p2.js/wiki/Home/0f28eb35ea615ced1084fb8e3b714a4524eefdb1#filtering-shape-collisions) says:

> In JavaScript, you can use 32 valid groups (Math.pow(2,0) up to Math.pow(2,31)). However, group Math.pow(2,0) won't collide with any other shape group, and group Math.pow(2,31) will collide with all other groups.

Doesn't it mean to say that `-1` (all 1 bits) will collide with all other masks?

**Comment by schteppe** [comment]
Hmm, yes that is true. Will update. Thanks.
