### ISSUE TITLE
Custom ID for bodies

### ISSUE THREAD

**Issue by 20zinnm** [schteppe/p2.js#260]
In the game I'm developing, I have a separate entity ID system. Is there a "supported" mechanism to override the ID of a body, or do I just modify the property and hope for the best?

**Comment by 20zinnm** [comment]
After re-evaluating my system this is no longer necessary.

**Comment by schteppe** [comment]
Cool. If someone else looks into this, the answer follows.

Each body has an `id` property which is used internally in the World to keep track of various things. Therefore it should not be modified.

```js
body.id = 123; // Don't do this
```

An alternative is to use an own property name:

```js
body.myCustomId = 123; // OK
```

(If you *really* want to modify the `id` property you can set it to an integer before you add it to the world. Make sure the id is unique among the other body id's in the same World)
