### ISSUE TITLE
How to implement a container rigid？ 

### ISSUE THREAD

**Issue by finscn** [schteppe/p2.js#278]
The container rigid  contains another rigid body .

Like a ball is inside a bottle.

**Comment by schteppe** [comment]
You could construct the bottle using multiple shapes inside one rigid body. Place shapes (boxes, or maybe capsules) along the contour of the bottle?

See compound shape demo here: http://schteppe.github.io/p2.js/demos/compound.html

**Comment by finscn** [comment]
I saw some engines support  A body  in another one.  It doesn't use many shapes/bodies.
Is there the feature in p2.js ?

**Comment by schteppe** [comment]
Sorry, I'm not sure what kind of feature you are referring to... could you post a screenshot or a link with a demonstration of a body in another one?

**Comment by finscn** [comment]
see this one :  http://kmdjs.github.io/dnt/demo13/index.html

**Comment by schteppe** [comment]
Oh, then it's easy. Put the 4 lines into the same body, with different offset and rotation. The compound shape demo contains what you need.

**Comment by finscn** [comment]
If it's a  circle , use many lines ?

**Comment by schteppe** [comment]
Yes. There's no "hollow circle" shape in p2.js.

**Comment by finscn** [comment]
I see. Thank you very much.

**Comment by Jeremboo** [comment]
My solution to create a container for the whole page. 
It could be useful for someone.

```javascript
const stageBody = new p2.Body();
world.addBody(stageBody);

const floor = new p2.Plane();
stageBody.addShape(floor, [0, -alfHeight]);
const roof = new p2.Plane();
stageBody.addShape(roof, [0, alfHeight], Math.PI);
const wallLeft = new p2.Plane();
stageBody.addShape(wallLeft, [-alfWidth, 0], -(Math.PI / 2));
const wallRigth = new p2.Plane();
stageBody.addShape(wallRigth, [alfWidth, 0], Math.PI / 2);
```
