### ISSUE TITLE
Continuous collision detection (CCD)

### ISSUE THREAD

**Issue by schteppe** [schteppe/p2.js#28]
Could be implemented by

1. Extrapolating bounding spheres/boxes of the dynamic bodies and estimate time of impact (TOI)
2. Root finding for a better estimate of the TOI and a point in time where the bodies actually intersect
3. Extrapolate the body to the TOI and wait there until the timestep ends

This should be quite easy to implement for dynamic vs static bodies. Right now I think that dynamic vs dynamic should be okay too, but we'll see about that :)

Maybe trigger CCD only when body speed reaches a limit? Or always use it?

A question is still how constraints connected to the body will behave when using this.

**Comment by schteppe** [comment]
@englercj @shakiba A first implementation of CCD is now in the latest master branch along with a demo (demos/ccd.html). I added parameters for speed threshold and TOI binary search iterations. Try it out :)

It should work for the shapes that are supported by raycasting (currently circles, rectangles and planes).

**Comment by englercj** [comment]
Nice! Been following that work, excited to try it out!

**Comment by enriqueto** [comment]
great job! 

I updated to Foot Chinko to phaser 2.3.0 that includes your last version. The physics work now wonderfully:

http://footchinko.com/games/footchinko/
