### ISSUE TITLE
Constraint should have id

### ISSUE THREAD

**Issue by ironchestgames** [schteppe/p2.js#281]
Hello,

The constraints does not have id like the bodies and the shapes. This would be useful.

My case is that I am reusing a graphics object (in pixi.js) but I need to be able to identify each constraint each frame. For now I'm just monkey-patching it, but it feels like something that should be present in p2.

Kind Regards,

**Comment by schteppe** [comment]
Hi. Since id’s aren’t required for the engine to work, i don’t think it should be added. Shapes and bodies require id’s so the overlaps can be tracked properly.
If you really need id properties on your constraints you can add them easily.
