### ISSUE TITLE
How to implement these 2 cases in dyn4j

### ISSUE THREAD

**Issue by finscn** [schteppe/p2.js#282]
I think dyn4j is the best Physics Engine  ( http://www.dyn4j.org/  )

There are 2 cases I don't know how to implement with P2.js , please help me, thanks .

------
the First : 
<img width="1025" alt="2017-02-05 2 31 17" src="https://cloud.githubusercontent.com/assets/288367/22620679/f23a17d8-eb4b-11e6-93bb-089c544e81d4.png">

It's named 'pulley' in dyn4j's demo . When Left Box down, the Right up.

------
the Second : 
<img width="1029" alt="2017-02-05 2 34 45" src="https://cloud.githubusercontent.com/assets/288367/22620687/0f41ab84-eb4c-11e6-8c3e-5b73a4bd8742.png">

The key is 'y' .   
The top part of 'y'  could collide with everything  , but bottom part doesn't.

Thanks.

**Comment by schteppe** [comment]
Ok, the 1st is a Pulley Joint, which is not available in p2.js (yet). You could try using 2 distance constraints and manually adjusting the lengths of them - it won't be as good as a pulley joint but it may be enough for your use case.

The 2nd one could be done by making the Y using 2 shapes, and disabling collision on the bottom shape. Or you could just skip adding the bottom part of the Y to the physics, but still render it.

**Comment by finscn** [comment]
Thanks.

The last question: 
Which features that dyn4j supported ，but p2 doesn't ?

**Comment by schteppe** [comment]
That one I cannot answer... I haven't used dyn4j or matter-js. Would be cool to see a compiled list of features supported in the three engines, side by side.

**Comment by finscn** [comment]
Thanks :) 
And please forgive me for my junior & stupid questions，  I'm a newbie of p2

**Comment by finscn** [comment]
Hi  @schteppe  , the Pulley Joint is in your Plan ? 
And is there a roadmap of p2.js ?
This is an amazing project , I hope it could be continue.

**Comment by schteppe** [comment]
Hi again. Pulley joint would be a natural step forward for p2.js. There is no roadmap, but I guess it would be cool if all features in box2d were in p2 too. It's just a hobby project and I don't work on it regularly. Help is appreciated!
