### ISSUE TITLE
how to make a Kinematic type body to DYNAMIC type

### ISSUE THREAD

**Issue by jimmyyao88** [schteppe/p2.js#295]
Hi Stefan ,Here is a Kinematic body move from left to right , i control another body to jump on that body , weirdly, the kinematic body go to the top .... what i want is the body back to DYNAMIC and down to the ground....
`world.on("beginContact",function(evt){`
`                if(evt.bodyA === platformBody && evt.bodyB === boxBody ) {`
`                    platformBody.type = p2.Body.DYNAMIC;`
`                };`
           ` })`

![bug](https://cloud.githubusercontent.com/assets/7344857/25781263/0b3e8834-336a-11e7-8b55-1a9579f2fea6.gif)

**Comment by jimmyyao88** [comment]
![may-07-2017 21-55-48](https://cloud.githubusercontent.com/assets/7344857/25781744/fd5361da-336f-11e7-8981-cf7af19a6f4b.gif)

**Comment by jimmyyao88** [comment]
@schteppe

**Comment by schteppe** [comment]
You probably have to set its mass and update the mass properties too. See https://github.com/schteppe/p2.js/wiki#mass-properties

If that doesn't work, you could also create a new body.

**Comment by jimmyyao88** [comment]
@schteppe ,hi Stefan,appreciate ur reply, I edit the example demo:'Canvas: Character demo' in readme,when the Character box jump and touch the platform body,I hope the platform body will drop down beacuse of the gravity,Here is the code:
`world.on('beginContact', function (evt){`
         `..code...`
         ` for(var i=0;i<platforms.length;i++){`
                `//follow what u said : update the body's mass property`
          	`platforms[i].mass = 1;`
          	`platforms[i].type = p2.Body.DYNAMIC;`
          	`console.log('updated')`
          `}`   
        `});`
![may-09-2017 13-17-18](https://cloud.githubusercontent.com/assets/7344857/25836518/ffa63ffc-34b9-11e7-9f94-b9c3f84c6d93.gif)
BUT , it seems dosent work, is it means the only way to make the body have influence by World Gravity and drop down is to create a new body?

**Comment by schteppe** [comment]
Did you try running . updateMassProperties() too? As in the wiki?

**Comment by jimmyyao88** [comment]
@schteppe AWESOME! LIFESAVER

**Comment by schteppe** [comment]
Cool! Updated [the wiki](https://github.com/schteppe/p2.js/wiki#mass-properties) to be more clear about changing `body.type`.
