### ISSUE TITLE
networked p2.js game example

### ISSUE THREAD

**Issue by enriqueto** [schteppe/p2.js#298]
Hi there,

has anyone successfully implemented a multiplayer game using p2 in the server?

I'd like to make a game for 2 players with basically 10 - 15 balls bouncing inside a square. It would need to be very responsive.

I'm thinking on implementing p2.js on both clients and server and do the corresponding corrections in the client side but I don't know if that makes sense.

**Comment by orlv** [comment]
Hi! Currently I'm developing a game with p2 on the server and it works great. 
You don't need p2 on the client, just send the positions from the server to the client.
Here the test server: http://celt.io

**Comment by enriqueto** [comment]
@orlv it looks nice! I think most of the io games take this approach. Clients just send inputs to the server.

Probably I'll start implementing p2 in the server side. However, the objects move faster in my game and I guess that I'll have to make corrections to the positions in the client side. Has anyone tried a faster game like a sports or a racing game?

**Comment by englercj** [comment]
I've done this running p2 on client and server. The client predicts and is corrected by the server on a tick interval.

**Comment by enriqueto** [comment]
@englercj using p2 on client and server, could you picture something like this running fluently?

https://www.miniclip.com/games/super-soccer-noggins/es/#t-w-c-C

**Comment by englercj** [comment]
> could you picture something like this running fluently?

Yes.

> Which tick interval are you using?

60hz

**Comment by enriqueto** [comment]
@englercj assuming an instance of a p2 world for each 2 players. Wouldn't that put a lot of pressure on the server?

**Comment by englercj** [comment]
@enriqueto "A lot" is relative, you should experiment with what your budget is and find what works for you. No one can tell you how your project will need to work, without knowing every detail about it. Try not to optimize prematurely, and just make something that works. Then make it faster/better.
