### ISSUE TITLE
interpolatedPosition does not start at position given in constructor

### ISSUE THREAD

**Issue by Jomik** [schteppe/p2.js#299]
I'm having an issue where it seems like for 3 steps, the interpolatedPosition interpolates from origin to the given starting position. It gives a flicker where all "Body" objects are at origin before they go to the actual positions. I've more or less copied the examples.
Outputting the interpolatedPosition gives 3 outputs around [0,0] before it jumps to [0,4.9].

This is the starting position I'm talking about:
https://github.com/Jomik/kingoftheplatformjs/blob/6b721e09abd3691d84f813f848f310c287b0cc5a/src/game.ts#L31

My source is here:
https://github.com/Jomik/kingoftheplatformjs/tree/6b721e09abd3691d84f813f848f310c287b0cc5a/src

**Comment by schteppe** [comment]
Already fixed but not yet released... See https://github.com/schteppe/p2.js/blob/master/src/objects/Body.js#L214

Try rebuilding the lib on the latest master branch.

**Comment by Jomik** [comment]
Oh, that's my bad.. I simply pulled p2 from npm :)
