### ISSUE TITLE
Polygon with holes in it?

### ISSUE THREAD

**Issue by schoening** [schteppe/p2.js#301]
Is this possible out of the box, or do I need to glue two+ polygons together?

**Comment by schteppe** [comment]
You should be able to use a single polygon. p2 will automatically convert to convex sub-shapes internally.

If you don't want p2 to do the conversion (for example, if you want to save some CPU usage) you should use many convex shapes instead, using the Convex class.

**Comment by schoening** [comment]
Ohh damn! P2 just keeps getting better and better!
