### ISSUE TITLE
[FEATURE] Gravitational points

### ISSUE THREAD

**Issue by moonheart08** [schteppe/p2.js#306]
I.e. a point in the world that pulls on other objects. Why? For things like, say, a black hole that wanders around the world and destroys objects that are pulled into it.

**Comment by schteppe** [comment]
You mean something like this?
```
world.on('postStep', function(){
    body.force[0] -= 100 * body.position[0];
    body.force[1] -= 100 * body.position[1];
    if(p2.vec2.length(body.position) < 2){
        // destroy logic
    }
});
```

**Comment by moonheart08** [comment]
@schteppe Similar, yes, but with support for multiple points.

**Comment by jtenner** [comment]
Yeah. Just loop over every point mass, then add the forces for each one yourself.

**Comment by moonheart08** [comment]
Yea, i see the point. Thanks. Gonna close.
