### ISSUE TITLE
[QUESTION] Unstable stack of boxes

### ISSUE THREAD

**Issue by jose-pleonasm** [schteppe/p2.js#317]
Hi,
I have a stack of boxes, which is falling apart without any initial impulse. As you can see here: https://codepen.io/jose-pleonasm/pen/WdVzYv

Why is this happening? Did I miss something or is it a some kind of issue?

**Comment by schteppe** [comment]
You should activate the "sleep" feature, which will deactivate objects when they are moving very slowly. This will prevent "creeping" as in your demo. See https://schteppe.github.io/p2.js/demos/sleep.html

**Comment by jose-pleonasm** [comment]
Thank you, it helps.
