### ISSUE TITLE
Sample Code Missing Function

### ISSUE THREAD

**Issue by BKTidswell** [schteppe/p2.js#319]
Hello, I am working to get started with p2. When I was trying to run the sample code it just said that renderCircleAtPosition was not an actual function. I grepped the function name in the entire repository and couldn't find it. Is this a function that I should know or be able to find? Or is it just a piece of pseudocode indicating that that is where I would run a circle rendering function I created?

**Comment by schteppe** [comment]
The sample code in the Readme is indeed not complete. You’ll have to implement renderCircleAtPosition yourself.
