### ISSUE TITLE
Have any demos about to get two bodies contact points?

### ISSUE THREAD

**Issue by guawoo** [schteppe/p2.js#325]
I can not found a demo about to get contact points when bodies collided. I only found a topic about this was a phaser approach, but my project is not phaser :(.

**Comment by Foxhunt** [comment]
Check [this](https://github.com/schteppe/p2.js/blob/2beb2750f42d29014e289cb803b7269d5b0edaad/demos/js/WebGLRenderer.js#L744) part of the Demo code. 

i use this function to detect collisions and spawn some particles at that point.

``` JavaScript
function findContacts(){
    for(let i = 0; i < world.narrowphase.contactEquations.length; i++){
        let eq = world.narrowphase.contactEquations[i]
        let bodyAPosition = eq.bodyA.position
        let contactPointA = eq.contactPointA
    
        let contactX = bodyAPosition[0] + contactPointA[0]
        let contactY = bodyAPosition[1] + contactPointA[1]

        spawnParticle(contactX, contactY)
    }
}
```

**Comment by guawoo** [comment]
oh, that great!  thank you so mush. :)
