### ISSUE TITLE
Toggling fixedX and fixedY on and off

### ISSUE THREAD

**Issue by anton980** [schteppe/p2.js#340]
Hello!  I am trying to toggle the fixedX/Y properties on runtime and it's having no affect on how the body behaves. 

Is there a trick to doing that?

Thank you!

**Comment by schteppe** [comment]
Yes, check the docs: https://github.com/schteppe/p2.js/blob/2beb2750f42d29014e289cb803b7269d5b0edaad/src/objects/Body.js#L174-L187
