### ISSUE TITLE
DOM rendering demo

### ISSUE THREAD

**Issue by schteppe** [schteppe/p2.js#45]
Because, why not. Probably using CSS transforms.

**Comment by jtenner** [comment]
Is there still a need for this? I think I might be able to help with this.  I have some knowledge of Dom sprites and would need some specifications on what the renderer/api would need to look like.

**Comment by petarov** [comment]
IMHO combining Ionic and p2 could be a huge win, although a DOM renderer would probably be an effort to reckon with.

**Comment by jtenner** [comment]
@petarov I could easily combine this with react, transforms, proper transitions, and some react magic.

I'll work up a gist with 300 balls running at 60fps bouncing off of 3 planes tomorrow

**Comment by jtenner** [comment]
It turns out react is not designed for 60fps animation, and the dom shouldn't be used that way either :).

However, it is possible and I am working on it.

It's going to take some time.

-Josh

**Comment by schteppe** [comment]
Hm, would it be more smooth/performant if you ran the physics at, say, 30fps and let the DOM do linear interpolation using CSS animation?

**Comment by jtenner** [comment]
I'm pushing updates way too fast to the dom, and it ends up eating a lot of memory and doing garbage collection.

Maintaining a set of dom nodes by giving them IDs in an index and pushing transforms and transitions to them is the fastest way and can be done at 60fps.

I'll get a working demo soon, I promise.

**Comment by schteppe** [comment]
Ok cool!

Another thing.. Should the animation data really go through React as state/props?

Here's a related post. Using jQuery, but I think http://stackoverflow.com/questions/25436445/using-jquery-plugins-that-transform-the-dom-in-react-components

**Comment by jtenner** [comment]
Yeah if I don't use react stuff it goes faster... so why use react at all ;-).

**Comment by schteppe** [comment]
Made a little fiddle around this... See http://jsfiddle.net/k98u8p0o/10/

The idea is to run physics at a slower rate than 60Hz and use CSS animations for the interpolation. Maybe you can use some parts of it. It seems to run OK on my phone as well :)

**Comment by schteppe** [comment]
Haha, having a bunch of fun with this

<img width="617" alt="p2-dom" src="https://cloud.githubusercontent.com/assets/1063152/11883283/239a3974-a512-11e5-9b51-762f3118e85c.png">

**Comment by mlynch** [comment]
I'm just having fun watching :)

To follow up to my comment, I did explore this a bit, using physicsjs though. If you want to see what I did, it's in this branch: https://github.com/driftyco/ionic/tree/wip-physics/contrib/physics.

Didn't find it was very useful or easy to use in practice, but fun as hell nonetheless :stuck_out_tongue:

**Comment by jtenner** [comment]
I highly suggest this:

```javascript
elem.style.transition = 'transform 20ms';
elem.style.transform = 'translate(' + + ')
```

You can go 60fps, just make the transition slightly longer than 20ms and the object will catch up.

Also, why set the transition more than once?

Simply use request animation frame and simply set transform: translate(x, y) rotate(rad) after physics?

**Comment by schteppe** [comment]
Yeah you're right. It feels like using CSS for interpolation is a bit unstable when updating so often, so I'm skipping it for now.

The DOM rendering demo has been [added to the repo](https://github.com/schteppe/p2.js/blob/master/examples/dom/index.html). Closing issue.
