### ISSUE TITLE
Best strategy to prevent a speedy body to move through another body without a collision

### ISSUE THREAD

**Issue by georgiee** [schteppe/p2.js#98]
Hi,
do you have some places where I should try to change the parameters?
Would it help to increase amount of substeps (default is 10 )? Is it the right parameter to touch? This would affect the overall performance and might be less optimal, wouldn't it ?

I already constraint the velocity of the moving object. I do this after the physics step (post render). Maybe it's too late in post render? But how could I do this in a substep ? Can you give me some advices in this question? 

Thank you!

**Comment by schteppe** [comment]
Awesome! Please try out the new CCD feature and see if it helps :)
